kernel:
  host: localhost
  port: 27931

team:
  name: <team-name>

adf:
  launcher:
    precompute: 0
  debug:
    flag: 0
  agent:
    moduleconfig:
      filename: config/module.yaml

  develop:
    flag: 1
    filename: config/development.json

  team:
    platoon:
      ambulance:
        count: 1
      fire:
        count: 0
      police:
        count: 0
    office:
      ambulance:
        count: -1
      fire:
        count: -1
      police:
        count: -1
