DefaultTacticsAmbulanceTeam:
  HumanDetector: src.team_name.module.complex.sample_human_detector.SampleHumanDetector
  Search: src.team_name.module.complex.sample_search.SampleSearch
  ExtendActionTransport: adf_core_python.implement.action.default_extend_action_transport.DefaultExtendActionTransport
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove
  CommandExecutorAmbulance: adf_core_python.implement.centralized.default_command_executor_ambulance.DefaultCommandExecutorAmbulance
  CommandExecutorScout: adf_core_python.implement.centralized.default_command_executor_scout.DefaultCommandExecutorScout

DefaultTacticsFireBrigade:
  HumanDetector: src.team_name.module.complex.sample_human_detector.SampleHumanDetector
  Search: src.team_name.module.complex.sample_search.SampleSearch
  ExtendActionRescue: adf_core_python.implement.action.default_extend_action_rescue.DefaultExtendActionRescue
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove
  CommandExecutorFire: adf_core_python.implement.centralized.default_command_executor_fire.DefaultCommandExecutorFire
  CommandExecutorScout: adf_core_python.implement.centralized.default_command_executor_scout.DefaultCommandExecutorScout

DefaultTacticsPoliceForce:
  RoadDetector: src.team_name.module.complex.sample_road_detector.SampleRoadDetector
  Search: src.team_name.module.complex.sample_search.SampleSearch
  ExtendActionClear: adf_core_python.implement.action.default_extend_action_clear.DefaultExtendActionClear
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove
  CommandExecutorPolice: adf_core_python.implement.centralized.default_command_executor_police.DefaultCommandExecutorPolice
  CommandExecutorScout: adf_core_python.implement.centralized.default_command_executor_scout.DefaultCommandExecutorScout

DefaultTacticsAmbulanceCenter:
  TargetAllocator: adf_core_python.implement.module.complex.default_ambulance_target_allocator.DefaultAmbulanceTargetAllocator
  CommandPicker: adf_core_python.implement.centralized.default_command_picker_ambulance.DefaultCommandPickerAmbulance

DefaultTacticsFireStation:
  TargetAllocator: adf_core_python.implement.module.complex.default_fire_target_allocator.DefaultFireTargetAllocator
  CommandPicker: adf_core_python.implement.centralized.default_command_picker_fire.DefaultCommandPickerFire

DefaultTacticsPoliceOffice:
  TargetAllocator: adf_core_python.implement.module.complex.default_police_target_allocator.DefaultPoliceTargetAllocator
  CommandPicker: adf_core_python.implement.centralized.default_command_picker_police.DefaultCommandPickerPolice

SampleSearch:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning
  Clustering: adf_core_python.implement.module.algorithm.k_means_clustering.KMeansClustering

SampleRoadDetector:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning

SampleHumanDetector:
  Clustering: adf_core_python.implement.module.algorithm.k_means_clustering.KMeansClustering

DefaultExtendActionClear:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning

DefaultExtendActionRescue:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning

DefaultExtendActionMove:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning

DefaultExtendActionTransport:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning

DefaultCommandExecutorAmbulance:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning
  ExtendActionTransport: adf_core_python.implement.action.default_extend_action_transport.DefaultExtendActionTransport
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove

DefaultCommandExecutorFire:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning
  ExtendActionFireRescue: adf_core_python.implement.action.default_extend_action_rescue.DefaultExtendActionRescue
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove

DefaultCommandExecutorPolice:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning
  ExtendActionClear: adf_core_python.implement.action.default_extend_action_clear.DefaultExtendActionClear
  ExtendActionMove: adf_core_python.implement.action.default_extend_action_move.DefaultExtendActionMove

DefaultCommandExecutorScout:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning

DefaultCommandExecutorScoutPolice:
  PathPlanning: adf_core_python.implement.module.algorithm.a_star_path_planning.AStarPathPlanning
  ExtendActionClear: adf_core_python.implement.action.default_extend_action_clear.DefaultExtendActionClear

MessageManager:
  PlatoonChannelSubscriber: adf_core_python.implement.module.communication.default_channel_subscriber.DefaultChannelSubscriber
  CenterChannelSubscriber: adf_core_python.implement.module.communication.default_channel_subscriber.DefaultChannelSubscriber
  PlatoonMessageCoordinator: adf_core_python.implement.module.communication.default_message_coordinator.DefaultMessageCoordinator
  CenterMessageCoordinator: adf_core_python.implement.module.communication.default_message_coordinator.DefaultMessageCoordinator
