kernel:
  host: localhost
  port: 27931

team:
  name: AIT-Rescue

adf:
  launcher:
    precompute: false
  debug:
    flag: false
  agent:
    moduleconfig:
      filename: config/module.yaml

  develop:
    flag: true
    filename: config/development.json

  team:
    platoon:
      ambulance:
        count: 100
      fire:
        count: 100
      police:
        count: 100
    office:
      ambulance:
        count: -1
      fire:
        count: -1
      police:
        count: -1
